# Generated by Django 6.0.3 on 2026-04-04 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(choices=[('developer', 'Developer'), ('professional', 'Professional'), ('social', 'Social'), ('reference', 'Reference')], default='reference', max_length=24)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['category', 'is_active', 'sort_order'], name='core_link_categor_4fa92b_idx'), models.Index(fields=['content_type', 'object_id'], name='core_link_content_9ea5d3_idx')],
            },
        ),
    ]
