# Generated by Django 6.0.3 on 2026-04-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_public_profile', '-updated_at'], name='users_public_updated_idx'),
        ),
    ]
