# Generated by Django 6.0.3 on 2026-04-04 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('abstract', models.TextField(blank=True)),
                ('tech_stack', models.JSONField(default=list)),
                ('user_roles', models.JSONField(default=list)),
                ('security', models.JSONField(default=dict)),
                ('references', models.JSONField(default=dict)),
                ('period', models.CharField(blank=True, max_length=64)),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('category', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
                ('quote', models.TextField(blank=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('thumbnail_image_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at', 'title'),
                'indexes': [models.Index(fields=['is_published', 'published_at'], name='portfolio_p_is_publ_7ef6ae_idx'), models.Index(fields=['category', 'role'], name='portfolio_p_categor_c1fe1d_idx'), models.Index(fields=['slug'], name='portfolio_p_slug_e96b08_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(max_length=240)),
                ('long_description', models.TextField()),
                ('icon_key', models.CharField(max_length=64)),
                ('features', models.JSONField(default=list)),
                ('tech_stack', models.JSONField(default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'title'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='portfolio_s_is_acti_2afda3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['project', 'sort_order'], name='portfolio_p_project_ef8fb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='portfolio.project')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['project', 'sort_order'], name='portfolio_p_project_d179d3_idx')],
            },
        ),
    ]
