# Generated by Django 6.0.3 on 2026-04-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='feature_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_metrics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='is_open_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_architecture',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='service',
            name='challenges_vs_solutions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='development_process',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='my_services',
            field=models.JSONField(default=list),
        ),
    ]
